version: '3'

services:
  message-service:
    image: message-service:latest

  user-service:
    image: user-service:latest
    command:
    - "--mysql.address=192.168.31.205"

  user-edge-service:
    image: user-edge-service:latest
    links:
    - user-service
    - message-service
    command:
    - "--redis.address=192.168.31.205"

  course-dubbo-service:
    image: course-dubbo-service:latest
    links:
    - user-service
    command:
    - "--mysql.address=192.168.31.205"
    - "--zookeeper.address=192.168.31.205"

  course-edge-service:
    image: course-edge-service:latest
    links:
    - user-edge-service
    command:
    - "--zookeeper.address=192.168.31.205"

  api-gateway-zuul:
    image: api-gateway-zuul:latest
    links:
    - user-edge-service
    - course-edge-service
    ports:
    - 8080:8080
