apiVersion: v1
kind: Service
metadata:
  labels:
    app: message-service
  name: message-service
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: message-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service-deployment
  template: 
    metadata:
      labels:
        app: message-service-deployment
    spec:
      containers:
      - name: message-service
        image: docker.io/578986218/message-service:latest
        ports:
        - containerPort: 9090

