apiVersion: v1
kind: Service
metadata:
  labels:
    app: course-service
  name: course-service
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: course-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service-deployment
  template:
    metadata:
      labels:
        app: course-service-deployment
    spec:
      containers:
      - name: course-service
        image: 578986218/course-service:latest
        ports:
        - containerPort: 20880
      - name: course-edge-service
        image: 578986218/course-edge-service:latest
        ports:
        - containerPort: 8081

