apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  ports:
  - name: user-edge-service-port
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: user-service-port
    port: 7911
    protocol: TCP
    targetPort: 7911
  selector:
    app: user-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: 578986218/user-service:latest
        ports:
        - containerPort: 7911
      - name: user-edge-service
        image: 578986218/user-edge-service:latest
        ports:
        - containerPort: 8082

